sberdevices/salutejs

packages/recognizer/src/index.ts
=> Add StringSimilarity export

packages/types/package.json
=> Right dist path

packages/scenario/README.md
=> Fix typo mistake

packages/scenario/src/lib/matchers.ts
=> Check variants array in intent matcher

packages/scenario/src/lib/createSaluteResponse.ts, packages/types/src/salute.ts
=> Support emotions in response

packages/recognizer/src/lib/smartAppBrain.ts
=> Add Brain default host

packages/scenario/src/lib/createSaluteResponse.ts, packages/types/src/salute.ts
=> fix: support 'deep_link' and 'server_action' suggests

packages/scenario/src/lib/i18n.spec.ts, packages/scenario/src/lib/i18n.ts, packages/types/src/i18n.ts
=> Get random phrase by key from i18n dictionary 

packages/recognizer-smartapp-brain/package.json
=> Wrong bin name 

packages/recognizer-smartapp-brain/README.md, packages/recognizer-smartapp-brain/package-lock.json, packages/recognizer-smartapp-brain/package.json, packages/recognizer-smartapp-brain/src/bin/brain.ts, packages/recognizer-smartapp-brain/src/lib/index.ts, packages/scenario/README.md, packages/scenario/src/lib/smartpay.ts
=> Support default env variables and dotenv 

packages/types/src/salute.ts
=> i18n options is optional 

packages/scenario/src/lib/createScenarioWalker.ts
=> intents are optional for createScenarioWalker 

packages/types/src/salute.ts
=> Make SaluteCommand payload optional

packages/recognizer-smartapp-brain/src/bin/brain.ts, packages/recognizer-smartapp-brain/src/lib/smartAppBrainSync.ts, packages/types/src/salute.ts
=> Make TextIntent type weaker

packages/scenario/src/lib/createSaluteRequest.ts, packages/types/src/systemMessage.ts
=> Cannot read property 'current_app' of undefined 

packages/scenario/src/lib/createSaluteResponse.ts, packages/types/src/salute.ts
Не хватает функции для отправки SSML ответа, можно добавить как отдельную, а можно в качестве параметра для функции: setPronounceText:
=> Функция для отправки SSML ответа

packages/recognizer-smartapp-brain/src/lib/smartAppBrainSync.ts
=> Cannot read property 'length' of null 

packages/scenario/src/lib/types/payment.ts, packages/scenario/src/lib/types/salute.ts
=> Can't extends SaluteRequestVariable

packages/scenario/src/lib/types/payment.ts
=> PaymentInvoiceStatuses matches to api

examples/todo/.env.sample
=> Добавить описание NEXT_PUBLIC_DEV_PHRASE для примера todo

packages/scenario/README.md
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.7.2-canary.184.0f139922763ac79f7f9ed858d56377db863ee775.0
npm install @salutejs/recognizer-string-similarity@0.7.2-canary.184.0f139922763ac79f7f9ed858d56377db863ee775.0
npm install @salutejs/scenario@0.7.2-canary.184.0f139922763ac79f7f9ed858d56377db863ee775.0
npm install @salutejs/storage-adapter-firebase@0.7.2-canary.184.0f139922763ac79f7f9ed858d56377db863ee775.0
npm install @salutejs/storage-adapter-memory@0.7.2-canary.184.0f139922763ac79f7f9ed858d56377db863ee775.0
yarn add @salutejs/recognizer-smartapp-brain@0.7.2-canary.184.0f139922763ac79f7f9ed858d56377db863ee775.0
yarn add …
```
=> docs: readme updated

packages/recognizer-smartapp-brain/src/bin/brain.ts, packages/recognizer-smartapp-brain/tsconfig.json
Resolves #185
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.7.2-canary.190.fe82a699f0d913bffed9f045312a8b92e1100e2e.0
npm install @salutejs/recognizer-string-similarity@0.7.2-canary.190.fe82a699f0d913bffed9f045312a8b92e1100e2e.0
npm install @salutejs/scenario@0.7.2-canary.190.fe82a699f0d913bffed9f045312a8b92e1100e2e.0
npm install @salutejs/storage-adapter-firebase@0.7.2-canary.190.fe82a699f0d913bffed9f045312a8b92e1100e2e.0
npm install @salutejs/storage-adapter-memory@0.7.2-canary.190.fe82a699f0d913bffed9f045312a8b92e1100e2e.0
yarn add @salutejs/recognizer-smartapp-brain@0.7.2-canary.190.fe82a699f0d913bffed9f045312a8b92e1100e2e.0
yarn add …
```
=> audiotour example. UnhandledPromiseRejectionWarning: Error: “@Tour” is not a system entity

.github/workflows/release.yml
Resolve #191
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.7.2-canary.192.4fb6dd53accbeab4d680c867a0a06fd678135209.0
npm install @salutejs/recognizer-string-similarity@0.7.2-canary.192.4fb6dd53accbeab4d680c867a0a06fd678135209.0
npm install @salutejs/scenario@0.7.2-canary.192.4fb6dd53accbeab4d680c867a0a06fd678135209.0
npm install @salutejs/storage-adapter-firebase@0.7.2-canary.192.4fb6dd53accbeab4d680c867a0a06fd678135209.0
npm install @salutejs/storage-adapter-memory@0.7.2-canary.192.4fb6dd53accbeab4d680c867a0a06fd678135209.0
yarn add @salutejs/recognizer-smartapp-brain@0.7.2-canary.192.4fb6dd53accbeab4d680c867a0a06fd678135209.0
yarn add …
```
=> There are no build step before autopublish 

.github/workflows/codeql-analysis.yml, .github/workflows/pr.yml, .github/workflows/release.yml, package.json, packages/recognizer-smartapp-brain/package.json, packages/recognizer-string-similarity/package.json, packages/scenario/package.json, packages/storage-adapter-firebase/package.json, packages/storage-adapter-memory/package.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.7.2-canary.193.f78b509aa2d9b2d19515149d9a4c3517023e8d94.0
npm install @salutejs/recognizer-string-similarity@0.7.2-canary.193.f78b509aa2d9b2d19515149d9a4c3517023e8d94.0
npm install @salutejs/scenario@0.7.2-canary.193.f78b509aa2d9b2d19515149d9a4c3517023e8d94.0
npm install @salutejs/storage-adapter-firebase@0.7.2-canary.193.f78b509aa2d9b2d19515149d9a4c3517023e8d94.0
npm install @salutejs/storage-adapter-memory@0.7.2-canary.193.f78b509aa2d9b2d19515149d9a4c3517023e8d94.0
yarn add @salutejs/recognizer-smartapp-brain@0.7.2-canary.193.f78b509aa2d9b2d19515149d9a4c3517023e8d94.0
yarn add …
```
=> fix: prepare step

.github/workflows/release.yml, packages/storage-adapter-firebase/src/lib/firebase.ts
<details>
<br />
```bash
npm install @salutejs/storage-adapter-firebase@0.9.1-canary.196.2c891d500deb81ea78e4533ff25996d7aa6a4100.0
yarn add @salutejs/storage-adapter-firebase@0.9.1-canary.196.2c891d500deb81ea78e4533ff25996d7aa6a4100.0
```
</details>
=> fix: eslint errors

packages/scenario/src/lib/createSaluteResponse.ts, packages/scenario/src/lib/i18n.spec.ts, packages/scenario/src/lib/types/salute.ts, packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.11.0-canary.199.e10eed33e8af65b1b3ede7fab7424a996b718b3d.0
npm install @salutejs/recognizer-string-similarity@0.11.0-canary.199.e10eed33e8af65b1b3ede7fab7424a996b718b3d.0
npm install @salutejs/scenario@0.11.0-canary.199.e10eed33e8af65b1b3ede7fab7424a996b718b3d.0
npm install @salutejs/storage-adapter-firebase@0.11.0-canary.199.e10eed33e8af65b1b3ede7fab7424a996b718b3d.0
npm install @salutejs/storage-adapter-memory@0.11.0-canary.199.e10eed33e8af65b1b3ede7fab7424a996b718b3d.0
yarn add @salutejs/recognizer-smartapp-brain@0.11.0-canary.199.e10eed33e8af65b1b3ede7fab7424a996b718b3d.0
yarn add …
```
=> feat: added rounded corners icons and updated system message types

packages/scenario/README.md, packages/scenario/src/index.ts, packages/scenario/src/lib/smartpush.ts, packages/scenario/src/lib/types/push.ts
Resolves #164 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.12.0-canary.200.bd6f65ebcf53b228a181f872b01f081da0d8e15c.0
npm install @salutejs/recognizer-string-similarity@0.12.0-canary.200.bd6f65ebcf53b228a181f872b01f081da0d8e15c.0
npm install @salutejs/scenario@0.12.0-canary.200.bd6f65ebcf53b228a181f872b01f081da0d8e15c.0
npm install @salutejs/storage-adapter-firebase@0.12.0-canary.200.bd6f65ebcf53b228a181f872b01f081da0d8e15c.0
npm install @salutejs/storage-adapter-memory@0.12.0-canary.200.bd6f65ebcf53b228a181f872b01f081da0d8e15c.0
yarn add @salutejs/recognizer-smartapp-brain@0.12.0-canary.200.bd6f65ebcf53b228a181f872b01f081da0d8e15c.0 …
```
=> SmartPush support

examples/chatapp-brain/package-lock.json, packages/scenario/README.md, packages/scenario/src/lib/matchers.ts
Resolves #203 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.13.0-canary.204.aa3658cca12d56aaed31f5227bc270f7ed72a1f4.0
npm install @salutejs/recognizer-string-similarity@0.13.0-canary.204.aa3658cca12d56aaed31f5227bc270f7ed72a1f4.0
npm install @salutejs/scenario@0.13.0-canary.204.aa3658cca12d56aaed31f5227bc270f7ed72a1f4.0
npm install @salutejs/storage-adapter-firebase@0.13.0-canary.204.aa3658cca12d56aaed31f5227bc270f7ed72a1f4.0
npm install @salutejs/storage-adapter-memory@0.13.0-canary.204.aa3658cca12d56aaed31f5227bc270f7ed72a1f4.0
yarn add @salutejs/recognizer-smartapp-brain@0.13.0-canary.204.aa3658cca12d56aaed31f5227bc270f7ed72a1f4.0 …
```
=> Add normalized param to text/regexp matchers

packages/scenario/src/lib/createSaluteResponse.ts, packages/scenario/src/lib/types/salute.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.14.0-canary.208.67e29cee591e1338c4ece530b8979f644e1fb844.0
npm install @salutejs/recognizer-string-similarity@0.14.0-canary.208.67e29cee591e1338c4ece530b8979f644e1fb844.0
npm install @salutejs/scenario@0.14.0-canary.208.67e29cee591e1338c4ece530b8979f644e1fb844.0
npm install @salutejs/storage-adapter-firebase@0.14.0-canary.208.67e29cee591e1338c4ece530b8979f644e1fb844.0
npm install @salutejs/storage-adapter-memory@0.14.0-canary.208.67e29cee591e1338c4ece530b8979f644e1fb844.0
yarn add @salutejs/recognizer-smartapp-brain@0.14.0-canary.208.67e29cee591e1338c4ece530b8979f644e1fb844.0
yarn add …
```
=> feat: policyRunApp

examples/todo/src/scenario/scenario.ts, packages/scenario/README.md, packages/scenario/src/lib/createSaluteRequest.ts, packages/scenario/src/lib/createSaluteResponse.ts, packages/scenario/src/lib/types/request.ts, packages/scenario/src/lib/types/response.ts, packages/scenario/src/lib/types/salute.ts
Resolves #201 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.15.0-canary.213.33a27c5e1aef42c5b5f819bf24f9ab6707c68ca7.0
npm install @salutejs/recognizer-string-similarity@0.15.0-canary.213.33a27c5e1aef42c5b5f819bf24f9ab6707c68ca7.0
npm install @salutejs/scenario@0.15.0-canary.213.33a27c5e1aef42c5b5f819bf24f9ab6707c68ca7.0
npm install @salutejs/storage-adapter-firebase@0.15.0-canary.213.33a27c5e1aef42c5b5f819bf24f9ab6707c68ca7.0
npm install @salutejs/storage-adapter-memory@0.15.0-canary.213.33a27c5e1aef42c5b5f819bf24f9ab6707c68ca7.0
yarn add @salutejs/recognizer-smartapp-brain@0.15.0-canary.213.33a27c5e1aef42c5b5f819bf24f9ab6707c68ca7.0 …
```
=> SmartProfile Integration

packages/scenario/src/lib/types/request.ts
Relates to #215
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.16.1-canary.217.fd08df209a503dec748aedf6f349daa06b2443f2.0
npm install @salutejs/recognizer-string-similarity@0.16.1-canary.217.fd08df209a503dec748aedf6f349daa06b2443f2.0
npm install @salutejs/scenario@0.16.1-canary.217.fd08df209a503dec748aedf6f349daa06b2443f2.0
npm install @salutejs/storage-adapter-firebase@0.16.1-canary.217.fd08df209a503dec748aedf6f349daa06b2443f2.0
npm install @salutejs/storage-adapter-memory@0.16.1-canary.217.fd08df209a503dec748aedf6f349daa06b2443f2.0
yarn add @salutejs/recognizer-smartapp-brain@0.16.1-canary.217.fd08df209a503dec748aedf6f349daa06b2443f2.0 …
```
=> Add city field to profile_data

packages/scenario/src/lib/createSaluteResponse.ts, packages/scenario/src/lib/types/response.ts, packages/scenario/src/lib/types/salute.ts
resolves #215 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.17.0-canary.218.a265f174e3973eeee8dcb932610cab86f94cd820.0
npm install @salutejs/recognizer-string-similarity@0.17.0-canary.218.a265f174e3973eeee8dcb932610cab86f94cd820.0
npm install @salutejs/scenario@0.17.0-canary.218.a265f174e3973eeee8dcb932610cab86f94cd820.0
npm install @salutejs/storage-adapter-firebase@0.17.0-canary.218.a265f174e3973eeee8dcb932610cab86f94cd820.0
npm install @salutejs/storage-adapter-memory@0.17.0-canary.218.a265f174e3973eeee8dcb932610cab86f94cd820.0
yarn add @salutejs/recognizer-smartapp-brain@0.17.0-canary.218.a265f174e3973eeee8dcb932610cab86f94cd820.0 …
```
=> Add chooseProfileData and getDetailedProfileData on res

packages/scenario/src/lib/types/salute.ts
#170 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.17.4-canary.225.819e25b792945b09c8adcf62e91d57f2441c4bc8.0
npm install @salutejs/recognizer-string-similarity@0.17.4-canary.225.819e25b792945b09c8adcf62e91d57f2441c4bc8.0
npm install @salutejs/scenario@0.17.4-canary.225.819e25b792945b09c8adcf62e91d57f2441c4bc8.0
npm install @salutejs/storage-adapter-firebase@0.17.4-canary.225.819e25b792945b09c8adcf62e91d57f2441c4bc8.0
npm install @salutejs/storage-adapter-memory@0.17.4-canary.225.819e25b792945b09c8adcf62e91d57f2441c4bc8.0
yarn add @salutejs/recognizer-smartapp-brain@0.17.4-canary.225.819e25b792945b09c8adcf62e91d57f2441c4bc8.0
yarn add …
```
=> Supports optional variables in SaluteRequest

packages/scenario/src/lib/createScenarioWalker.ts, packages/scenario/src/lib/missingVariables.ts, packages/scenario/src/lib/types/salute.ts
Resolves #214
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.17.6-canary.229.bdcb1cc4bfa473d53ce5af4ca9b4bd20f99f0f91.0
npm install @salutejs/recognizer-string-similarity@0.17.6-canary.229.bdcb1cc4bfa473d53ce5af4ca9b4bd20f99f0f91.0
npm install @salutejs/scenario@0.17.6-canary.229.bdcb1cc4bfa473d53ce5af4ca9b4bd20f99f0f91.0
npm install @salutejs/storage-adapter-firebase@0.17.6-canary.229.bdcb1cc4bfa473d53ce5af4ca9b4bd20f99f0f91.0
npm install @salutejs/storage-adapter-memory@0.17.6-canary.229.bdcb1cc4bfa473d53ce5af4ca9b4bd20f99f0f91.0
yarn add @salutejs/recognizer-smartapp-brain@0.17.6-canary.229.bdcb1cc4bfa473d53ce5af4ca9b4bd20f99f0f91.0
yarn …
```
=> Slot filling bug

packages/recognizer-smartapp-brain/src/lib/index.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.17.7-canary.230.a56bf99fcac359065fa963703d114615d428e702.0
yarn add @salutejs/recognizer-smartapp-brain@0.17.7-canary.230.a56bf99fcac359065fa963703d114615d428e702.0
```
</details>
=> fix: smartapp brain take 10 best intents

packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.18.0-canary.234.9f24b34ef5b1833ba9879d00a17a9ca7f9828d56.0
npm install @salutejs/recognizer-string-similarity@0.18.0-canary.234.9f24b34ef5b1833ba9879d00a17a9ca7f9828d56.0
npm install @salutejs/scenario@0.18.0-canary.234.9f24b34ef5b1833ba9879d00a17a9ca7f9828d56.0
npm install @salutejs/storage-adapter-firebase@0.18.0-canary.234.9f24b34ef5b1833ba9879d00a17a9ca7f9828d56.0
npm install @salutejs/storage-adapter-memory@0.18.0-canary.234.9f24b34ef5b1833ba9879d00a17a9ca7f9828d56.0
yarn add @salutejs/recognizer-smartapp-brain@0.18.0-canary.234.9f24b34ef5b1833ba9879d00a17a9ca7f9828d56.0
yarn add …
```
=> Support hints in system message

packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.19.0-canary.247.601208b404bbea7464da0fce0df9258325e8a810.0
npm install @salutejs/recognizer-string-similarity@0.19.0-canary.247.601208b404bbea7464da0fce0df9258325e8a810.0
npm install @salutejs/scenario@0.19.0-canary.247.601208b404bbea7464da0fce0df9258325e8a810.0
npm install @salutejs/storage-adapter-firebase@0.19.0-canary.247.601208b404bbea7464da0fce0df9258325e8a810.0
npm install @salutejs/storage-adapter-memory@0.19.0-canary.247.601208b404bbea7464da0fce0df9258325e8a810.0
yarn add @salutejs/recognizer-smartapp-brain@0.19.0-canary.247.601208b404bbea7464da0fce0df9258325e8a810.0
yarn add …
```
=> feat: Добавлен EMBEDDED_APP в AppType.

packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.21.0-canary.257.f5255b560cad6ed19a0aa104a969a33e388b0c41.0
npm install @salutejs/recognizer-string-similarity@0.21.0-canary.257.f5255b560cad6ed19a0aa104a969a33e388b0c41.0
npm install @salutejs/scenario@0.21.0-canary.257.f5255b560cad6ed19a0aa104a969a33e388b0c41.0
npm install @salutejs/storage-adapter-firebase@0.21.0-canary.257.f5255b560cad6ed19a0aa104a969a33e388b0c41.0
npm install @salutejs/storage-adapter-memory@0.21.0-canary.257.f5255b560cad6ed19a0aa104a969a33e388b0c41.0
yarn add @salutejs/recognizer-smartapp-brain@0.21.0-canary.257.f5255b560cad6ed19a0aa104a969a33e388b0c41.0
yarn add …
```
=> feat: Добавлен экшн StartSmartSearchAction

packages/scenario/src/lib/createSaluteResponse.ts, packages/scenario/src/lib/types/response.ts, packages/scenario/src/lib/types/salute.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.21.0-canary.258.5ceffd1924ffaea18e6da56dd1489bfb92d5e96c.0
npm install @salutejs/recognizer-string-similarity@0.21.0-canary.258.5ceffd1924ffaea18e6da56dd1489bfb92d5e96c.0
npm install @salutejs/scenario@0.21.0-canary.258.5ceffd1924ffaea18e6da56dd1489bfb92d5e96c.0
npm install @salutejs/storage-adapter-firebase@0.21.0-canary.258.5ceffd1924ffaea18e6da56dd1489bfb92d5e96c.0
npm install @salutejs/storage-adapter-memory@0.21.0-canary.258.5ceffd1924ffaea18e6da56dd1489bfb92d5e96c.0
yarn add @salutejs/recognizer-smartapp-brain@0.21.0-canary.258.5ceffd1924ffaea18e6da56dd1489bfb92d5e96c.0
yarn add …
```
=> feat: override frontend endpoint

packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.23.0-canary.261.88378c8d151c48959de136b250dd5abcc5e6ab7a.0
npm install @salutejs/recognizer-string-similarity@0.23.0-canary.261.88378c8d151c48959de136b250dd5abcc5e6ab7a.0
npm install @salutejs/scenario@0.23.0-canary.261.88378c8d151c48959de136b250dd5abcc5e6ab7a.0
npm install @salutejs/storage-adapter-firebase@0.23.0-canary.261.88378c8d151c48959de136b250dd5abcc5e6ab7a.0
npm install @salutejs/storage-adapter-memory@0.23.0-canary.261.88378c8d151c48959de136b250dd5abcc5e6ab7a.0
yarn add @salutejs/recognizer-smartapp-brain@0.23.0-canary.261.88378c8d151c48959de136b250dd5abcc5e6ab7a.0
yarn add …
```
=> feat: добавлен тип карточки simple_list

packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.24.0-canary.267.46f1e043439ba24689554b63fbcfd7a6364d1937.0
npm install @salutejs/recognizer-string-similarity@0.24.0-canary.267.46f1e043439ba24689554b63fbcfd7a6364d1937.0
npm install @salutejs/scenario@0.24.0-canary.267.46f1e043439ba24689554b63fbcfd7a6364d1937.0
npm install @salutejs/storage-adapter-firebase@0.24.0-canary.267.46f1e043439ba24689554b63fbcfd7a6364d1937.0
npm install @salutejs/storage-adapter-memory@0.24.0-canary.267.46f1e043439ba24689554b63fbcfd7a6364d1937.0
yarn add @salutejs/recognizer-smartapp-brain@0.24.0-canary.267.46f1e043439ba24689554b63fbcfd7a6364d1937.0
yarn add …
```
=> feat: добавлен type для карточки simple_list

packages/scenario/src/lib/createScenarioWalker.ts
Closes #242 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.24.1-canary.272.d99c85c3bedbc5fa30c0dd820ecbf72671b9b710.0
npm install @salutejs/recognizer-string-similarity@0.24.1-canary.272.d99c85c3bedbc5fa30c0dd820ecbf72671b9b710.0
npm install @salutejs/scenario@0.24.1-canary.272.d99c85c3bedbc5fa30c0dd820ecbf72671b9b710.0
npm install @salutejs/storage-adapter-firebase@0.24.1-canary.272.d99c85c3bedbc5fa30c0dd820ecbf72671b9b710.0
npm install @salutejs/storage-adapter-memory@0.24.1-canary.272.d99c85c3bedbc5fa30c0dd820ecbf72671b9b710.0
yarn add @salutejs/recognizer-smartapp-brain@0.24.1-canary.272.d99c85c3bedbc5fa30c0dd820ecbf72671b9b710.0
yarn …
```
=> fix: Асинхронный хендлер RUN_APP

packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.24.2-canary.278.a8f2fdfb853365ca5ada2b5b5c549529378c273b.0
npm install @salutejs/recognizer-string-similarity@0.24.2-canary.278.a8f2fdfb853365ca5ada2b5b5c549529378c273b.0
npm install @salutejs/scenario@0.24.2-canary.278.a8f2fdfb853365ca5ada2b5b5c549529378c273b.0
npm install @salutejs/storage-adapter-firebase@0.24.2-canary.278.a8f2fdfb853365ca5ada2b5b5c549529378c273b.0
npm install @salutejs/storage-adapter-memory@0.24.2-canary.278.a8f2fdfb853365ca5ada2b5b5c549529378c273b.0
yarn add @salutejs/recognizer-smartapp-brain@0.24.2-canary.278.a8f2fdfb853365ca5ada2b5b5c549529378c273b.0
yarn add …
```
=> Список ячеек типа right

packages/scenario/src/lib/smartpush.ts, packages/scenario/src/lib/types/push.ts, packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.24.0-canary.262.c90a43bc8e906d70579d9893ef001f5db2329f9b.0
npm install @salutejs/recognizer-string-similarity@0.24.0-canary.262.c90a43bc8e906d70579d9893ef001f5db2329f9b.0
npm install @salutejs/scenario@0.24.0-canary.262.c90a43bc8e906d70579d9893ef001f5db2329f9b.0
npm install @salutejs/storage-adapter-firebase@0.24.0-canary.262.c90a43bc8e906d70579d9893ef001f5db2329f9b.0
npm install @salutejs/storage-adapter-memory@0.24.0-canary.262.c90a43bc8e906d70579d9893ef001f5db2329f9b.0
yarn add @salutejs/recognizer-smartapp-brain@0.24.0-canary.262.c90a43bc8e906d70579d9893ef001f5db2329f9b.0
yarn add …
```
=> feat: Определить значения поверхностей и каналов
